#!/usr/bin/env bash
# Reproduce the three main feature-selection strategies with fixed full-feature references.
set -euo pipefail

usage() {
    cat <<'EOF'
Usage: bash reproduce_main.sh [options]

  --mode retrain|evaluate|fresh   Default: retrain
    retrain  Copy saved splits and graphs; train all 11 models per dataset.
    evaluate Copy saved splits, graphs and models; recompute RMIA CSVs.
    fresh    Prepare data and learn graphs, then train and evaluate.
  --dataset NAME|all             Default: all seven datasets
  --output DIRECTORY             Default: reproduction/main_<mode> (project-relative)
  --python EXECUTABLE            Default: python (active environment)
  -h, --help                     Show this message

Install requirements.txt first. Training uses 100 epochs, batch size 256,
2 CPU threads, three target models and eight fixed full-feature references.
The output directory must not already exist. No supplied results are overwritten.
Fresh mode may download data and relearns graphs from original inputs and labels.
EOF
}

mode=retrain
dataset_choice=all
output=
python_bin=python
while [[ $# -gt 0 ]]; do
    case "$1" in
        --mode|--dataset|--output|--python)
            if [[ $# -lt 2 || -z "$2" ]]; then
                printf 'Missing value for %s\n' "$1" >&2
                exit 2
            fi
            case "$1" in
                --mode) mode=$2 ;;
                --dataset) dataset_choice=$2 ;;
                --output) output=$2 ;;
                --python) python_bin=$2 ;;
            esac
            shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) printf 'Unknown option: %s\n' "$1" >&2; usage >&2; exit 2 ;;
    esac
done
case "$mode" in
    retrain|evaluate|fresh) ;;
    *) printf 'Invalid mode: %s\n' "$mode" >&2; exit 2 ;;
esac
all_datasets=(ACSEmployment ACSPublicCoverage ACSMobility ACSIncome ACSTravelTime half-a-million-lifestyle covertype)
if [[ "$dataset_choice" == all ]]; then
    datasets=("${all_datasets[@]}")
else
    case "$dataset_choice" in
        ACSEmployment|ACSPublicCoverage|ACSMobility|ACSIncome|ACSTravelTime|half-a-million-lifestyle|covertype)
            datasets=("$dataset_choice") ;;
        *) printf 'Invalid dataset: %s\n' "$dataset_choice" >&2; exit 2 ;;
    esac
fi

project_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
cd "$project_dir"
output=${output:-reproduction/main_$mode}
export PYTHONHASHSEED=0
export PYTHONDONTWRITEBYTECODE=1

# Copy only inputs; result CSVs are generated by RMIA.py.
"$python_bin" - "$mode" "$output" "${datasets[@]}" <<'PYCODE'
from pathlib import Path
import shutil
import sys

mode, destination, *datasets = sys.argv[1:]
root = Path(destination)
root.mkdir(parents=True, exist_ok=False)
if mode != 'fresh':
    for dataset in datasets:
        for folder, name in [('data', 'data.npz'), ('results', 'causal_graph.json')]:
            target = root / folder / dataset
            target.mkdir(parents=True, exist_ok=True)
            shutil.copy2(Path(folder) / dataset / name, target / name)
        if mode == 'evaluate':
            shutil.copytree(Path('models') / dataset, root / 'models' / dataset)
PYCODE

for dataset in "${datasets[@]}"; do
    printf '\n=== %s: %s ===\n' "$dataset" "$mode"
    if [[ "$mode" == fresh ]]; then
        "$python_bin" data_prepare.py --dataset "$dataset" --root "$output" --seed 42 --year 2018 --state CA
        "$python_bin" Learn_causal_graph.py --dataset "$dataset" --root "$output" \
            --bins 5 --max-indegree 3 --max-iter 10000
    fi
    if [[ "$mode" != evaluate ]]; then
        "$python_bin" train.py --dataset "$dataset" --root "$output" \
            --epochs 100 --batch-size 256 --threads 2
    fi
    "$python_bin" RMIA.py --dataset "$dataset" --root "$output" --gamma 2
done

# Combine the newly generated per-dataset tables.
"$python_bin" - "$output" "${datasets[@]}" <<'PYCODE'
from pathlib import Path
import sys
import pandas as pd

root = Path(sys.argv[1])
tables = []
for dataset in sys.argv[2:]:
    tables.append(pd.read_csv(root / 'results' / dataset / 'comparison.csv'))
output = root / 'results/comparison.csv'
pd.concat(tables, ignore_index=True).to_csv(output, index=False)
print('Combined results:', output)
PYCODE
